### ISSUE TITLE
Is it possible to show the RECENT list of books when just typing “ib”?

### ISSUE THREAD

**Issue by realliyifei** [codycodes/alfred-books#14]
Now when typing "ib", the workflow shows the books in a weird order. IDK what it is, but guess it's a default order based on the oldest installed time.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/32441766/92990559-fe6b9780-f50f-11ea-891d-77ff5e3e3323.png">

IMO it would be helpful if it shows the list of *recent* books or at least provides this option.

![image](https://user-images.githubusercontent.com/32441766/92990582-22c77400-f510-11ea-865c-63107ea48100.png)

---

I opened three issues and it's a lot lol. It depends on how much time you have :) 

Take it easy. If you're too busy now, I would be happy to provide a pull request once I have time.

**Comment by codycodes** [comment]
This would be a really great feature which I think is useful as the default behavior of just using `ib`. I appreciate including the screenshot because I realized that in the database that stores all of the Books app's information, there is no column for sorting of the books. At first I was a bit concerned because I didn't know how it's being accomplished in the app, but I realized that the Books app is probably just looking as the last access time for a file to do its sorting by most recent.

Since we know the paths of the Books files from the Books database (how this workflow accesses its data), we can probably just compare all of these files to the current time to determine which is most recent. It could work as the default behavior using `ib` and potentially could also be accomplished with a switch `ib -r` which might allow you to filter down the results sorted by most recent.

**Comment by realliyifei** [comment]
> It could work as the default behavior using ib and potentially could also be accomplished with a switch ib -r which might allow you to filter down the results sorted by most recent.

Although I personally prefer the former, both of them are GREAT ideas!

> I realized that the Books app is probably just looking as the last access time for a file to do its sorting by most recent.

And yes, that's how it seems to work. It probably just does the recent search as MacOS does it in the general file system.

**Comment by codycodes** [comment]
Implemented in the latest release! Thanks again for the great idea! Feel free to update with `ib workflow:update`

At first I found that grabbing the modified time, or `atime` worked for .pdf files, but not other files which are contained in the Books app. I found by looking into what was being changed by the Books app that it's the `st_ctime` on Unix, which is "the time of most recent metadata change on Unix" from the [docs](https://docs.python.org/3.8/library/os.html#os.stat_result.st_ctime)

As a side affect of sorting, any books which don't have a path that points to an existing file automatically get placed at the end. It's still really easy to filter to these, but if I get to it I'd like to figure out a way to download and open these files directly via Alfred.
