### ISSUE TITLE
Structure issues

### ISSUE THREAD

**Issue by xilopaint** [codycodes/alfred-books#6]
You should have `icon.png` and `info.plit` in `src` and invoke your script from the Script Filter with `python alfred_books.py "{query}"` only, so no need to `cd ./src`.

Therefore, your `.alfredworkflow` file should be bundled with the whole content of `src` and nothing else.

**Comment by codycodes** [comment]
Thanks for the clarification; I appreciate it!

**Comment by xilopaint** [comment]
[Workflow Installer.zip](https://github.com/codycodes/alfred-books/files/3364492/Workflow.Installer.zip)

After doing these changes use the workflow above to symlink `src` and install your workflow. You just need to select `src` and invoke the Alfred actions panel from there to finally choose the `Install Workflow` action.

**Comment by codycodes** [comment]
Following your instructions, I've now moved the files and symlinked everything properly; my dev flow feels a million times better now. Thanks for the help again!

**Comment by xilopaint** [comment]
You still have to set the workflow version:

![](https://user-images.githubusercontent.com/11052366/60409564-8b8c3000-9b9a-11e9-9f2f-02f4370fd06c.png)

**Comment by codycodes** [comment]
@xilopaint oops, that's a bit embarrassing! See I actually had the version number added, but since I'm on Alfred 4 and developing for Alfred 3, I must have discarded the changes for the `info.plist`file thus discarding the version number in there (so that this workflow could still be used with Alfred 3). I'll ensure the version is correctly set from now on and update the release. Thanks a ton!

edit:
Updated and fixed. I've got a process setup now for future releases and I wouldn't have known how to set it up so cleanly and efficiently without your help. Now to focus on more features and bug fixes; thanks again!
